/** Facade: domain split into entity clusters; import path stays stable. */
export type {
	AntigravityOauthToken,
	AuthJsonBlob,
	CatalogModel,
	ClaudeOauthToken,
	CursorLoginToken,
	Effort,
	EngineConfig,
	EngineKind,
	ModelCatalog,
	ModelName,
	SecretWrite,
	WriteSecretsResult,
} from "./domain/engine.ts";
export {
	EFFORTS,
	ENGINE_KINDS,
	antigravityOauthToken,
	authJsonBlob,
	catalogHasModel,
	catalogModel,
	claudeOauthToken,
	cursorLoginToken,
	effort,
	engineKind,
	modelCatalog,
	modelName,
	parseAntigravityOauthFields,
} from "./domain/engine.ts";
export type {
	AppSecretWrite,
	Bot,
	GithubAppId,
	GithubAppPrivateKey,
	GithubAppSlug,
	GithubInstallationId,
	GithubToken,
	GithubUserToken,
} from "./domain/github-app.ts";
export {
	SECRET_NAMES,
	githubAppId,
	githubAppInstallationId,
	githubAppPrivateKey,
	githubAppSlug,
	githubToken,
	githubUserToken,
} from "./domain/github-app.ts";
export type {
	ActionRef,
	ContentHash,
	EventDecision,
	FixPhrase,
	IdempotencyMarker,
	IgnoreReason,
	Job,
	ParsedEvent,
	Phrases,
	Plan,
	PlanResult,
	RunResult,
	Trigger,
	TriggerPhrase,
	WorkflowYaml,
} from "./domain/job.ts";
export {
	DEFAULT_FIX_PHRASE,
	actionRef,
	contentHash,
	fixPhrase,
	mentionTrigger,
	triggerPhrase,
	workflowYaml,
} from "./domain/job.ts";
export type { NonEmpty, ParseResult } from "./domain/parse.ts";
export {
	brandNumber,
	brandString,
	exhaustive,
	parseInvalid,
	parseOk,
	requireSingleLine,
	requireText,
} from "./domain/parse.ts";
export type {
	AbsolutePath,
	CommitSha,
	GithubLogin,
	RepoId,
	RepoName,
	RepoOwner,
	RepoPath,
	RepoRef,
	RepoRefParts,
} from "./domain/repo.ts";
export {
	absolutePath,
	commitSha,
	githubLogin,
	parseRepoRef,
	repoId,
	repoName,
	repoOwner,
	repoPath,
	repoRef,
	repoRefFromApi,
	repoRefFromParts,
} from "./domain/repo.ts";
export type {
	CommentId,
	CommentMarkdown,
	Finding,
	GithubReviewEvent,
	LineCount,
	LineNumber,
	LineRange,
	PullNumber,
	ReplacementText,
	ReviewEventChoice,
	ReviewId,
	ReviewMarkdown,
	ReviewReport,
	Suggestion,
	SuggestionMarkdown,
} from "./domain/review.ts";
export {
	commentId,
	commentMarkdown,
	inclusiveEnd,
	lineCount,
	lineNumber,
	lineRange,
	pullNumber,
	replacementText,
	reviewEventChoice,
	reviewId,
	reviewMarkdown,
	suggestionMarkdown,
} from "./domain/review.ts";
