#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

_WIZARD_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$_WIZARD_DIR/.." && pwd)
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/apps/web/.env.local"
WEB_DIR="$REPO_ROOT/apps/web"

github_app_new_url() {
  local lab="$1" name="$2" owner="$3"
  python3 - "$lab" "$name" "$owner" <<'PY'
import sys
from urllib.parse import urlencode

lab, name, owner = sys.argv[1], sys.argv[2], sys.argv[3]
lab = lab.rstrip("/")
params = [
    ("name", name),
    ("url", lab),
    ("callback_urls[]", f"{lab}/api/auth/callback/github"),
    ("public", "true"),
    ("webhook_active", "true"),
    ("webhook_url", f"{lab}/api/github-webhook"),
    ("administration", "write"),
    ("contents", "write"),
    ("workflows", "write"),
    ("actions", "write"),
    ("issues", "write"),
    ("pull_requests", "write"),
    ("emails", "read"),
    ("events[]", "pull_request"),
    ("events[]", "issue_comment"),
    ("events[]", "pull_request_review_comment"),
]
base = "https://github.com/settings/apps/new"
if owner:
    base = f"https://github.com/organizations/{owner}/settings/apps/new"
print(f"{base}?{urlencode(params)}", end="")
PY
}

pem_file_to_env_line() {
  python3 - "$1" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1]).expanduser()
text = path.read_text().strip().replace("\r\n", "\n")
if "BEGIN" not in text or "PRIVATE KEY" not in text:
    sys.stderr.write("not a PEM file\n")
    sys.exit(1)
print(text.replace("\n", "\\n"), end="")
PY
}

env_unescape_nl() {
  python3 -c 'import sys; print(sys.stdin.read().replace("\\n", "\n"), end="")'
}

minify_json_line() {
  python3 -c 'import json,sys; json.dump(json.load(sys.stdin), sys.stdout, separators=(",", ":"))'
}

unprefix_assignment() {
  local key="$1" value="$2"
  while [[ "$value" == "$key="* ]]; do
    value="${value#"$key="}"
  done
  printf '%s' "$value"
}

put_wrangler_secret() {
  local name="$1" value="$2"
  value=$(unprefix_assignment "$name" "$value")
  if [[ -z "$value" ]]; then
    note "skipping $name (empty in $ENV_FILE)"
    return 0
  fi
  if (
    cd "$WEB_DIR"
    printf '%s' "$value" | bunx wrangler secret put "$name"
  ); then
    printf '  %s✓ set%s Worker secret %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  SKIPPED+=("Worker secret $name")
  warn "wrangler secret put $name failed"
}

github_apps_list_url() {
  if [[ -n "${GITHUB_APP_OWNER:-}" ]]; then
    printf '%s' "https://github.com/organizations/${GITHUB_APP_OWNER}/settings/apps"
  else
    printf '%s' "https://github.com/settings/apps"
  fi
}

github_app_settings_url() {
  if [[ -z "${HOSTED_APP_SLUG:-}" ]]; then
    github_apps_list_url
    return
  fi
  if [[ -n "${GITHUB_APP_OWNER:-}" ]]; then
    printf '%s' "https://github.com/organizations/${GITHUB_APP_OWNER}/settings/apps/${HOSTED_APP_SLUG}"
  else
    printf '%s' "https://github.com/settings/apps/${HOSTED_APP_SLUG}"
  fi
}

ingest_antigravity_json() {
  local src="$1" json
  if [[ -z "$src" || ! -f "$src" ]]; then
    return 1
  fi
  if ! json=$(minify_json_line < "$src"); then
    warn "file is not JSON"
    return 1
  fi
  write_env CATALOG_ANTIGRAVITY_OAUTH "$json"
}

github_app_form_steps() {
  local lab="${VITE_LAB_URL%/}"
  step "Homepage URL: ${lab}"
  step "Callback URL: ${lab}/api/auth/callback/github"
  step "Webhook URL: ${lab}/api/github-webhook"
  step "Webhook secret: paste the value from the previous stage."
  step "Repository permissions Read and write: Administration, Contents, Workflows, Actions, Issues, Pull requests."
  step "Subscribe to events: pull_request, issue_comment, pull_request_review_comment."
  step "Leave Request user authorization (OAuth) during installation unticked."
  step "Leave Enable Device Flow unticked."
  step "Account permissions: Email addresses Read-only."
  step "Organization permissions: all No access."
  step "Where can this GitHub App be installed: Any account."
  step "Create GitHub App."
}

generate_hex() {
  openssl rand -hex 32
}

ensure_wrangler_login() {
  if ( cd "$WEB_DIR" && bunx wrangler whoami >/dev/null 2>&1 ); then
    return 0
  fi
  say "wrangler needs a Cloudflare login. A browser window will open."
  ( cd "$WEB_DIR" && bunx wrangler login ) || warn "wrangler login failed"
}

ask_required() {
  local key="$1" prompt="$2" mode="${3:-ask}"
  while true; do
    if [[ "$mode" == secret ]]; then
      ask_secret "$key" "$prompt"
    else
      ask "$key" "$prompt"
    fi
    if [[ -n "${!key}" ]]; then
      write_env "$key" "${!key}"
      return 0
    fi
    warn "$key is required to boot Lab"
    if confirm "Continue with $key blank?"; then
      return 0
    fi
  done
}

patch_wrangler_vars() {
  python3 - "$WEB_DIR/wrangler.jsonc" \
    "$(_existing HOSTED_APP_CLIENT_ID || true)" \
    "$(_existing HOSTED_APP_SLUG || true)" \
    "$(_existing VITE_ACTION_REF || true)" \
    "$(_existing VITE_LAB_URL || true)" \
    "$(_existing VITE_SOURCE_REPO_URL || true)" <<'PY'
import json
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
pairs = {
    "HOSTED_APP_CLIENT_ID": sys.argv[2],
    "HOSTED_APP_SLUG": sys.argv[3],
    "VITE_ACTION_REF": sys.argv[4],
    "VITE_LAB_URL": sys.argv[5],
    "VITE_SOURCE_REPO_URL": sys.argv[6],
}
text = path.read_text()
for key, value in pairs.items():
    if not value:
        continue
    escaped = json.dumps(value)[1:-1]
    text, n = re.subn(
        rf'("{key}":\s*")(?:\\.|[^"\\])*(")',
        lambda m, escaped=escaped: m.group(1) + escaped + m.group(2),
        text,
        count=1,
    )
    if n != 1:
        sys.stderr.write(f"did not replace {key}\n")
        sys.exit(1)
path.write_text(text)
PY
}

patch_wrangler_after() {
  local marker="$1" key="$2" value="$3"
  python3 - "$WEB_DIR/wrangler.jsonc" "$marker" "$key" "$value" <<'PY'
import json
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
marker, key, value = sys.argv[2], sys.argv[3], sys.argv[4]
text = path.read_text()
idx = text.find(marker)
if idx < 0:
    sys.stderr.write(f"missing {marker}\n")
    sys.exit(1)
head, tail = text[:idx], text[idx:]
escaped = json.dumps(value)[1:-1]
tail, n = re.subn(
    rf'("{key}":\s*")(?:\\.|[^"\\])*(")',
    lambda m, escaped=escaped: m.group(1) + escaped + m.group(2),
    tail,
    count=1,
)
if n != 1:
    sys.stderr.write(f"did not replace {key} after {marker}\n")
    sys.exit(1)
path.write_text(head + tail)
PY
}

d1_uuid_from_text() {
  python3 -c "$(cat <<'PY'
import json
import re
import sys

text = sys.stdin.read()
try:
    data = json.loads(text)
    for key in ("uuid", "database_id", "id"):
        if isinstance(data, dict) and data.get(key):
            print(data[key], end="")
            raise SystemExit(0)
except json.JSONDecodeError:
    pass
m = re.search(r'"database_id":\s*"([0-9a-f-]{36})"', text)
if not m:
    m = re.search(
        r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
        text,
        re.I,
    )
if m:
    print(m.group(1) if m.lastindex else m.group(0), end="")
    raise SystemExit(0)
sys.exit(1)
PY
)"
}

d1_id_from_list() {
  local name="$1"
  python3 -c "$(cat <<'PY'
import json
import sys

name = sys.argv[1]
raw = sys.stdin.read()
try:
    data = json.loads(raw)
except json.JSONDecodeError:
    sys.exit(1)
rows = data if isinstance(data, list) else data.get("result") or []
for row in rows:
    if row.get("name") != name:
        continue
    ident = row.get("uuid") or row.get("database_id") or row.get("id")
    if ident:
        print(ident, end="")
        raise SystemExit(0)
sys.exit(1)
PY
)" "$name"
}

kv_id_from_list() {
  local title="$1"
  python3 -c "$(cat <<'PY'
import json
import sys

title = sys.argv[1]
raw = sys.stdin.read()
try:
    data = json.loads(raw)
except json.JSONDecodeError:
    sys.exit(1)
rows = data if isinstance(data, list) else data.get("namespaces") or data.get("result") or []
for row in rows:
    if row.get("title") != title:
        continue
    ident = row.get("id") or row.get("namespace_id")
    if ident:
        print(ident, end="")
        raise SystemExit(0)
sys.exit(1)
PY
)" "$title"
}

kv_id_from_text() {
  python3 -c "$(cat <<'PY'
import json
import re
import sys

text = sys.stdin.read()
try:
    data = json.loads(text)
    if isinstance(data, dict):
        nss = data.get("kv_namespaces") or []
        if nss and nss[0].get("id"):
            print(nss[0]["id"], end="")
            raise SystemExit(0)
        if data.get("id"):
            print(data["id"], end="")
            raise SystemExit(0)
except json.JSONDecodeError:
    pass
m = re.search(r'"id":\s*"([0-9a-fA-F]{32})"', text)
if m:
    print(m.group(1), end="")
    raise SystemExit(0)
sys.exit(1)
PY
)"
}

lab_hostname() {
  python3 - "$1" <<'PY'
from urllib.parse import urlparse
import sys

host = urlparse(sys.argv[1]).hostname or ""
print(host, end="")
PY
}

is_loopback_host() {
  case "$1" in
    localhost|127.0.0.1|::1|"") return 0 ;;
    *) return 1 ;;
  esac
}

wrangler_routes_pattern() {
  python3 - "$WEB_DIR/wrangler.jsonc" <<'PY'
import pathlib
import re
import sys

text = pathlib.Path(sys.argv[1]).read_text()
idx = text.find('"routes"')
if idx < 0:
    sys.exit(1)
m = re.search(r'"pattern":\s*"([^"]*)"', text[idx:])
if not m:
    sys.exit(1)
print(m.group(1), end="")
PY
}

wrangler_routes_enabled() {
  python3 - "$WEB_DIR/wrangler.jsonc" <<'PY'
import pathlib
import re
import sys

text = pathlib.Path(sys.argv[1]).read_text()
idx = text.find('"routes"')
if idx < 0:
    sys.exit(1)
m = re.search(r'"enabled":\s*(true|false)', text[idx:])
if not m:
    sys.exit(1)
print(m.group(1), end="")
PY
}

patch_routes_enabled() {
  local enabled="$1"
  python3 - "$WEB_DIR/wrangler.jsonc" "$enabled" <<'PY'
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
enabled = sys.argv[2]
text = path.read_text()
idx = text.find('"routes"')
if idx < 0:
    sys.exit(1)
head, tail = text[:idx], text[idx:]
tail, n = re.subn(r'"enabled":\s*(true|false)', f'"enabled": {enabled}', tail, count=1)
if n != 1:
    sys.stderr.write("did not replace routes enabled\n")
    sys.exit(1)
path.write_text(head + tail)
PY
}

TOTAL_STAGES=22

banner "hakasebot Lab setup"

# ── 1. Public URLs ───────────────────────────────────────────────────────
stage "Public Lab URLs"
say "Writes apps/web/.env.local. CI has no secrets.*, so this wizard never runs gh secret set."
if [[ ! -f "$ENV_FILE" ]]; then
  cp "$WEB_DIR/.env.example" "$ENV_FILE"
  note "copied apps/web/.env.example → $ENV_FILE"
fi
ask VITE_LAB_URL "Public Lab origin (local default http://localhost:47821):"
ask VITE_SOURCE_REPO_URL "Source repo URL:"
ask VITE_ACTION_REF "Action ref (owner/repo@ref):"
write_env VITE_LAB_URL "$VITE_LAB_URL"
write_env VITE_SOURCE_REPO_URL "$VITE_SOURCE_REPO_URL"
write_env VITE_ACTION_REF "$VITE_ACTION_REF"
if [[ "$VITE_LAB_URL" == *localhost* || "$VITE_LAB_URL" == *127.0.0.1* || "$VITE_LAB_URL" == *::1* ]]; then
  warn "GitHub will not deliver webhooks to loopback. Sign-in callback still works locally."
fi

# ── 2. better-auth ────────────────────────────────────────────────────────
stage "BETTER_AUTH_SECRET"
say "better-auth seals session cookies with this. Rotating it signs everyone out."
if [[ -n "$(_existing BETTER_AUTH_SECRET || true)" ]]; then
  if confirm "Rotate BETTER_AUTH_SECRET?"; then
    BETTER_AUTH_SECRET=$(bunx --bun @better-auth/cli secret | tail -n1 | tr -d '\r')
  else
    BETTER_AUTH_SECRET=$(_existing BETTER_AUTH_SECRET)
    note "keeping the existing secret"
  fi
else
  say "Generating one with bunx --bun @better-auth/cli secret."
  BETTER_AUTH_SECRET=$(bunx --bun @better-auth/cli secret | tail -n1 | tr -d '\r')
fi
BETTER_AUTH_SECRET=$(unprefix_assignment BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET")
write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"

# ── 3. Webhook HMAC ───────────────────────────────────────────────────────
stage "HOSTED_APP_WEBHOOK_SECRET"
say "GitHub cannot put this in the prefill URL. We generate it here, then you paste it on the App form."
if [[ -n "$(_existing HOSTED_APP_WEBHOOK_SECRET || true)" ]]; then
  if confirm "Rotate HOSTED_APP_WEBHOOK_SECRET?"; then
    HOSTED_APP_WEBHOOK_SECRET=$(generate_hex)
  else
    HOSTED_APP_WEBHOOK_SECRET=$(_existing HOSTED_APP_WEBHOOK_SECRET)
    note "keeping the existing webhook secret"
  fi
else
  HOSTED_APP_WEBHOOK_SECRET=$(generate_hex)
fi
write_env HOSTED_APP_WEBHOOK_SECRET "$HOSTED_APP_WEBHOOK_SECRET"
say "Paste this into GitHub's Webhook secret field on the next stage:"
printf '  %s%s%s\n' "$BOLD" "$HOSTED_APP_WEBHOOK_SECRET" "$RESET"
pause "Copied the webhook secret?"

# ── 4. Create Hosted bot App ────────────────────────────────────────────
stage "Create the Hosted bot App"
say "One Hosted bot App is Lab sign-in and the Bot. GitHub's form still lives under Developer settings → GitHub Apps."
ask GITHUB_APP_NAME "App name on GitHub (becomes the slug):"
ask GITHUB_APP_OWNER "Owner org slug (empty = your personal account):"
if confirm "Register a new Hosted bot App now?"; then
  if command -v python3 >/dev/null 2>&1; then
    APP_NEW_URL=$(github_app_new_url "$VITE_LAB_URL" "$GITHUB_APP_NAME" "$GITHUB_APP_OWNER")
  else
    warn "python3 missing; opening a blank New GitHub App form. Fill the steps below by hand."
    APP_NEW_URL="$(github_apps_list_url)/new"
  fi
  open_url "$APP_NEW_URL"
  github_app_form_steps
  pause "Created the App?"
else
  ask HOSTED_APP_SLUG "Existing App slug (github.com/apps/<slug>):"
  write_env HOSTED_APP_SLUG "$HOSTED_APP_SLUG"
  open_url "$(github_app_settings_url)"
  step "Webhook secret: paste the value from the previous stage if this App does not already have one, then Save."
  pause "Webhook secret saved on the existing App, or already set?"
fi

# ── 6. Client ID + slug ────────────────────────────────────────────────
stage "Client ID and slug"
say "Client ID is public (JWT iss). The slug is the last path segment of https://github.com/apps/<slug>. Slug can stay blank until the bot is needed."
open_url "$(github_apps_list_url)"
step "Copy the slug from the public page URL, github.com/apps/<slug>. Enter keeps it blank."
ask HOSTED_APP_SLUG "Paste the App slug:"
write_env HOSTED_APP_SLUG "$HOSTED_APP_SLUG"
open_url "$(github_app_settings_url)"
step "Copy Client ID from About."
ask_required HOSTED_APP_CLIENT_ID "Paste the Client ID:"

# ── 6. Client secret ────────────────────────────────────────────────────
stage "Client secret"
say "This is the OAuth Client secret, not the PEM. Generate a new one; GitHub shows it once. Lab will not boot without it."
open_url "$(github_app_settings_url)"
step "Client secrets → Generate a new client secret → copy it."
ask_required HOSTED_APP_CLIENT_SECRET "Paste the Client secret:" secret

# ── 8. PEM ──────────────────────────────────────────────────────────────
stage "Private key PEM"
say "HOSTED_APP_PRIVATE_KEY must be the downloaded PEM, not the Client secret. Stored as a single .env line with \\n. Lab sign-in boots without it; the bot needs it."
if confirm "Store a private key now?"; then
  open_url "$(github_app_settings_url)"
  step "Private keys → Generate a private key. A .pem file downloads."
  ask PEM_PATH "Path to the downloaded .pem file:"
  PEM_FILE="${PEM_PATH/#\~/$HOME}"
  if [[ -z "$PEM_PATH" || ! -f "$PEM_FILE" ]]; then
    warn "no file at that path; PEM left unset"
  elif HOSTED_APP_PRIVATE_KEY=$(pem_file_to_env_line "$PEM_FILE"); then
    write_env HOSTED_APP_PRIVATE_KEY "$HOSTED_APP_PRIVATE_KEY"
  else
    warn "could not read a PEM from that file; left unset"
  fi
else
  note "skipped"
fi

# ── 8. Host console ───────────────────────────────────────────────────────
stage "HOST_CONSOLE_TOKEN"
say "/host is 404 until this is set. Generate a long random token; paste it in the browser later."
if [[ -n "$(_existing HOST_CONSOLE_TOKEN || true)" ]]; then
  if confirm "Rotate HOST_CONSOLE_TOKEN?"; then
    HOST_CONSOLE_TOKEN=$(generate_hex)
  else
    HOST_CONSOLE_TOKEN=$(_existing HOST_CONSOLE_TOKEN)
    note "keeping the existing token"
  fi
else
  if confirm "Generate HOST_CONSOLE_TOKEN now?"; then
    HOST_CONSOLE_TOKEN=$(generate_hex)
  else
    HOST_CONSOLE_TOKEN=""
  fi
fi
if [[ -n "$HOST_CONSOLE_TOKEN" ]]; then
  write_env HOST_CONSOLE_TOKEN "$HOST_CONSOLE_TOKEN"
else
  note "left unset"
fi

# ── 9. LAB_DEV_USER ──────────────────────────────────────────────────────
stage "LAB_DEV_USER"
say "On loopback, LAB_DEV_USER=1 treats the User as signed in (ADR-0012). Never put this on the Worker."
write_env LAB_DEV_USER "1"
note "wrote LAB_DEV_USER=1"

# ── 10. Dev PAT ─────────────────────────────────────────────────────────
stage "LAB_DEV_GITHUB_TOKEN"
say "Optional. GitHub writes from Lab still need a PAT with repo and workflow. Do not reuse a Cloud Agent gh token."
if confirm "Set LAB_DEV_GITHUB_TOKEN now?"; then
  open_url "https://github.com/settings/tokens/new?scopes=repo,workflow&description=hakasebot-lab-dev"
  step "Classic token. Leave repo and workflow ticked. Generate token. Copy it once."
  ask_secret LAB_DEV_GITHUB_TOKEN "Paste the PAT:"
  write_env LAB_DEV_GITHUB_TOKEN "$LAB_DEV_GITHUB_TOKEN"
else
  note "skipped"
fi

# ── 11. Catalog Anthropic ─────────────────────────────────────────────
stage "Catalog: Anthropic"
say "Optional. Missing catalog keys make that engine's picker fail; custom-string still works."
if confirm "Set CATALOG_ANTHROPIC_API_KEY now?"; then
  open_url "https://console.anthropic.com/settings/keys"
  step "Create Key → copy it."
  ask_secret CATALOG_ANTHROPIC_API_KEY "Paste the Anthropic key:"
  write_env CATALOG_ANTHROPIC_API_KEY "$CATALOG_ANTHROPIC_API_KEY"
else
  note "skipped"
fi

# ── 12. Catalog OpenAI ─────────────────────────────────────────────────
stage "Catalog: OpenAI"
if confirm "Set CATALOG_OPENAI_API_KEY now?"; then
  open_url "https://platform.openai.com/api-keys"
  step "Create new secret key → copy it."
  ask_secret CATALOG_OPENAI_API_KEY "Paste the OpenAI key:"
  write_env CATALOG_OPENAI_API_KEY "$CATALOG_OPENAI_API_KEY"
else
  note "skipped"
fi

# ── 13. Catalog xAI ─────────────────────────────────────────────────────
stage "Catalog: xAI"
say "Listing needs prepaid team credits but does not spend them. Restrict the key so it cannot chat."
if confirm "Set CATALOG_XAI_API_KEY now?"; then
  open_url "https://console.x.ai"
  step "API Keys → Create API Key."
  step "Chat models only, Models endpoint only, 1 token per minute."
  ask_secret CATALOG_XAI_API_KEY "Paste the xAI key:"
  write_env CATALOG_XAI_API_KEY "$CATALOG_XAI_API_KEY"
else
  note "skipped"
fi

# ── 14. Catalog Cursor ──────────────────────────────────────────────────
stage "Catalog: Cursor"
say "User API key from the Cursor dashboard. hakasebot maps it to CURSOR_API_KEY at spawn."
if confirm "Set CATALOG_CURSOR_API_KEY now?"; then
  open_url "https://cursor.com/dashboard/api"
  step "User API Keys → create a key → copy the secret from the dialog (shown once)."
  ask_secret CATALOG_CURSOR_API_KEY "Paste the Cursor user API key:"
  write_env CATALOG_CURSOR_API_KEY "$CATALOG_CURSOR_API_KEY"
else
  note "skipped"
fi

# ── 15. Catalog Antigravity ─────────────────────────────────────────────
stage "Catalog: Antigravity"
say "CATALOG_ANTIGRAVITY_OAUTH is the agy OAuth JSON from the OS keyring (service=gemini, username=antigravity). secret-tool fails on KDE; python libsecret dump works."
if confirm "Set CATALOG_ANTIGRAVITY_OAUTH now?"; then
  CATALOG_ANTIGRAVITY_OAUTH=""
  if confirm "Try dumping the keyring with python3 now?"; then
    if CATALOG_ANTIGRAVITY_OAUTH=$(
      python3 - <<'PY'
import gi
gi.require_version("Secret", "1")
from gi.repository import Secret
s = Secret.Service.get_sync(Secret.ServiceFlags.OPEN_SESSION, None)
i = s.search_sync(
    None,
    {"service": "gemini", "username": "antigravity"},
    Secret.SearchFlags.UNLOCK | Secret.SearchFlags.LOAD_SECRETS,
    None,
)[0]
print(i.get_secret().get().decode(), end="")
PY
    ) && CATALOG_ANTIGRAVITY_OAUTH=$(printf '%s' "$CATALOG_ANTIGRAVITY_OAUTH" | minify_json_line); then
      write_env CATALOG_ANTIGRAVITY_OAUTH "$CATALOG_ANTIGRAVITY_OAUTH"
    else
      warn "keyring dump failed"
      CATALOG_ANTIGRAVITY_OAUTH=""
    fi
  fi
  if [[ -z "$CATALOG_ANTIGRAVITY_OAUTH" ]]; then
    ask_secret CATALOG_ANTIGRAVITY_OAUTH "Paste the OAuth JSON (one line), or Enter to use a file:"
    if [[ -n "$CATALOG_ANTIGRAVITY_OAUTH" ]]; then
      if CATALOG_ANTIGRAVITY_OAUTH=$(printf '%s' "$CATALOG_ANTIGRAVITY_OAUTH" | minify_json_line); then
        write_env CATALOG_ANTIGRAVITY_OAUTH "$CATALOG_ANTIGRAVITY_OAUTH"
      else
        warn "paste was not JSON"
        CATALOG_ANTIGRAVITY_OAUTH=""
      fi
    fi
  fi
  if [[ -z "$CATALOG_ANTIGRAVITY_OAUTH" ]]; then
    ask ANTIGRAVITY_JSON_PATH "Path to the OAuth JSON file:"
    ingest_antigravity_json "${ANTIGRAVITY_JSON_PATH/#\~/$HOME}" || note "left unset"
  fi
else
  note "skipped"
fi

# ── 16. Worker public vars ─────────────────────────────────────────────
stage "Cloudflare Worker public vars"
say "These stay wrangler.jsonc vars, not secrets."
note "HOSTED_APP_CLIENT_ID=$(_existing HOSTED_APP_CLIENT_ID || true)"
note "HOSTED_APP_SLUG=$(_existing HOSTED_APP_SLUG || true)"
note "VITE_ACTION_REF=$(_existing VITE_ACTION_REF || true)"
note "VITE_LAB_URL=$(_existing VITE_LAB_URL || true)"
note "VITE_SOURCE_REPO_URL=$(_existing VITE_SOURCE_REPO_URL || true)"
warn "bun run build inlines VITE_* from .env.local. A localhost VITE_LAB_URL will bake into the client bundle."
if confirm "Write those five keys into apps/web/wrangler.jsonc vars now?"; then
  if patch_wrangler_vars; then
    printf '  %s✓ wrote%s wrangler.jsonc vars\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("wrangler.jsonc vars")
    warn "could not patch wrangler.jsonc"
  fi
fi
if confirm "Delete Worker secret HOSTED_APP_CLIENT_ID if it exists, so the wrangler.jsonc var wins?"; then
  ensure_wrangler_login
  ( cd "$WEB_DIR" && bunx wrangler secret delete HOSTED_APP_CLIENT_ID ) || note "nothing to delete, or delete failed"
fi

# ── 17. D1 ──────────────────────────────────────────────────────────────
stage "Cloudflare D1"
say "D1 holds vault, repo, and wake rows. Binding is DB, database name hakasebot. Lookup is by name on this account, not the committed database_id."
if confirm "Bind D1 hakasebot in wrangler.jsonc?"; then
  ensure_wrangler_login
  D1_ID=""
  if D1_LIST=$( cd "$WEB_DIR" && bunx wrangler d1 list --json 2>/dev/null ); then
    D1_ID=$(printf '%s' "$D1_LIST" | d1_id_from_list hakasebot) || D1_ID=""
    [[ -n "$D1_ID" ]] && note "found existing D1 hakasebot"
  fi
  if [[ -z "$D1_ID" ]]; then
    if confirm "No D1 named hakasebot on this account. Create it?"; then
      if D1_OUT=$( cd "$WEB_DIR" && bunx wrangler d1 create hakasebot ); then
        printf '%s\n' "$D1_OUT"
        D1_ID=$(printf '%s' "$D1_OUT" | d1_uuid_from_text) || D1_ID=""
      fi
    fi
  fi
  if [[ -n "$D1_ID" ]] && patch_wrangler_after '"d1_databases"' database_id "$D1_ID"; then
    printf '  %s✓ wrote%s database_id %s\n' "$GREEN" "$RESET" "$D1_ID"
  else
    SKIPPED+=("D1 hakasebot")
    warn "could not bind D1 hakasebot"
  fi
else
  note "skipped"
fi

# ── 18. KV ──────────────────────────────────────────────────────────────
stage "Cloudflare KV"
say "KV holds the Model catalog cache. Binding is MODEL_CATALOG. Lookup is by title on this account."
if confirm "Bind KV MODEL_CATALOG in wrangler.jsonc?"; then
  ensure_wrangler_login
  KV_ID=""
  if KV_LIST=$( cd "$WEB_DIR" && bunx wrangler kv namespace list 2>/dev/null ); then
    KV_ID=$(printf '%s' "$KV_LIST" | kv_id_from_list MODEL_CATALOG) || KV_ID=""
    [[ -n "$KV_ID" ]] && note "found existing KV MODEL_CATALOG"
  fi
  if [[ -z "$KV_ID" ]]; then
    if confirm "No KV titled MODEL_CATALOG on this account. Create it?"; then
      if KV_OUT=$( cd "$WEB_DIR" && bunx wrangler kv namespace create MODEL_CATALOG ); then
        printf '%s\n' "$KV_OUT"
        KV_ID=$(printf '%s' "$KV_OUT" | kv_id_from_text) || KV_ID=""
      fi
    fi
  fi
  if [[ -n "$KV_ID" ]] && patch_wrangler_after '"kv_namespaces"' id "$KV_ID"; then
    printf '  %s✓ wrote%s MODEL_CATALOG id %s\n' "$GREEN" "$RESET" "$KV_ID"
  else
    SKIPPED+=("KV MODEL_CATALOG")
    warn "could not bind KV MODEL_CATALOG"
  fi
else
  note "skipped"
fi

# ── 19. Custom domain ─────────────────────────────────────────────────
stage "Cloudflare custom domain"
LAB_HOST=$(lab_hostname "$(_existing VITE_LAB_URL || true)")
ROUTE_PATTERN=$(wrangler_routes_pattern || true)
say "Wrangler deploy creates the Custom Domain DNS record. The hostname must already be a zone on this Cloudflare account, with no leftover CNAME."
if is_loopback_host "$LAB_HOST"; then
  note "VITE_LAB_URL is loopback. Not writing a custom domain. Disabling wrangler.jsonc routes so deploy cannot attach ${ROUTE_PATTERN:-the committed hostname}."
  if patch_routes_enabled false; then
    printf '  %s✓ wrote%s routes enabled false\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("disable custom domain")
    warn "could not disable routes; refuse deploy later"
  fi
else
  note "hostname: $LAB_HOST"
  open_url "https://dash.cloudflare.com"
  step "Add this hostname as a site if it is not already a zone. Wait until the zone is Active."
  step "If a CNAME already exists for ${LAB_HOST}, delete it."
  pause "Zone is Active and the hostname is free of a CNAME?"
  if confirm "Write ${LAB_HOST} into wrangler.jsonc routes as a custom domain?"; then
    if patch_wrangler_after '"routes"' pattern "$LAB_HOST" && patch_routes_enabled true; then
      printf '  %s✓ wrote%s routes pattern %s enabled true\n' "$GREEN" "$RESET" "$LAB_HOST"
    else
      SKIPPED+=("custom domain $LAB_HOST")
      warn "could not patch routes"
    fi
  fi
fi

# ── 20. Deploy ────────────────────────────────────────────────────────
stage "Deploy Worker"
say "bun run deploy is bun run build && wrangler deploy. That publishes the Worker, binds D1 and KV, and creates the Custom Domain if wrangler.jsonc routes are enabled. Observability is already on in wrangler.jsonc."
ROUTE_PATTERN=$(wrangler_routes_pattern || true)
ROUTES_ON=$(wrangler_routes_enabled || true)
if is_loopback_host "$LAB_HOST"; then
  warn "VITE_LAB_URL is loopback. Deploy uses wrangler.jsonc (routes pattern ${ROUTE_PATTERN:-unknown})."
  if [[ "$ROUTES_ON" == true ]]; then
    warn "routes are still enabled; not deploying so the committed custom domain is not attached."
    note "skipped"
  elif confirm "Deploy now (workers.dev / disabled custom domain)?"; then
    ensure_wrangler_login
    bun run deploy || { SKIPPED+=("bun run deploy"); warn "deploy failed"; }
  else
    note "skipped. wrangler secret put needs this Worker to exist first."
  fi
elif [[ -n "$LAB_HOST" && -n "$ROUTE_PATTERN" && "$ROUTE_PATTERN" != "$LAB_HOST" ]]; then
  warn "VITE_LAB_URL host is $LAB_HOST but wrangler.jsonc routes pattern is $ROUTE_PATTERN."
  if confirm "Deploy now?"; then
    ensure_wrangler_login
    bun run deploy || { SKIPPED+=("bun run deploy"); warn "deploy failed"; }
  else
    note "skipped. wrangler secret put needs this Worker to exist first."
  fi
elif confirm "Deploy now?"; then
  ensure_wrangler_login
  bun run deploy || { SKIPPED+=("bun run deploy"); warn "deploy failed"; }
else
  note "skipped. wrangler secret put needs this Worker to exist first."
fi

# ── 21. Worker secrets ──────────────────────────────────────────────
stage "Cloudflare Worker secrets"
say "wrangler secret put of credential keys from .env.local. The Worker must already exist. Does not put LAB_DEV_* or public branding."
if confirm "Put Worker secrets now?"; then
  ensure_wrangler_login
  put_wrangler_secret BETTER_AUTH_SECRET "$(_existing BETTER_AUTH_SECRET || true)"
  put_wrangler_secret HOST_CONSOLE_TOKEN "$(_existing HOST_CONSOLE_TOKEN || true)"
  put_wrangler_secret HOSTED_APP_CLIENT_SECRET "$(_existing HOSTED_APP_CLIENT_SECRET || true)"
  put_wrangler_secret HOSTED_APP_WEBHOOK_SECRET "$(_existing HOSTED_APP_WEBHOOK_SECRET || true)"
  put_wrangler_secret HOSTED_APP_PRIVATE_KEY "$( _existing HOSTED_APP_PRIVATE_KEY | env_unescape_nl || true )"
  put_wrangler_secret CATALOG_ANTHROPIC_API_KEY "$(_existing CATALOG_ANTHROPIC_API_KEY || true)"
  put_wrangler_secret CATALOG_OPENAI_API_KEY "$(_existing CATALOG_OPENAI_API_KEY || true)"
  put_wrangler_secret CATALOG_XAI_API_KEY "$(_existing CATALOG_XAI_API_KEY || true)"
  put_wrangler_secret CATALOG_CURSOR_API_KEY "$(_existing CATALOG_CURSOR_API_KEY || true)"
  put_wrangler_secret CATALOG_ANTIGRAVITY_OAUTH "$(_existing CATALOG_ANTIGRAVITY_OAUTH || true)"
else
  note "skipped"
fi

# ── 22. Remote D1 migrations ────────────────────────────────────────
stage "Remote D1 migrations"
say "Applies apps/web/migrations to remote D1 hakasebot (vault, repo, and wake tables)."
if confirm "Run bun run db:migrate:remote?"; then
  bun run db:migrate:remote || { SKIPPED+=("db:migrate:remote"); warn "migrate failed"; }
else
  note "skipped"
fi
note "local lab: bun run dev → http://localhost:47821"

finish
